# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '35 15 * * *'

jobs:
  build:

    runs-on: macOs-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Install npx
      run: npm i -g npx
    - name: Get relevant chromedriver print current version of chrome on worker
      run: npx @puppeteer/browsers install chromedriver@`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version | cut -d ' ' -f 3`   
    - name: List content of this file
      run: ls ./chromedriver | grep `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version | cut -d ' ' -f 3`    
    - name: Build with Maven
      run: mvn -B package --file ./legit/pom.xml
    - name: Run basic E2E test
      run: mvn clean test -DsuiteXmlFile=./legit/suite/login_test_suite.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
